# Generated by Django 4.1.3 on 2023-01-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='staff_id',
            new_name='staff_username',
        ),
        migrations.AlterField(
            model_name='course_content',
            name='content_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='course_content',
            name='course_content_description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='course_content',
            name='course_content_tag',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
